### ISSUE TITLE
Installing as R package

### ISSUE THREAD

**Issue by belkhir-nacim** [kerschke/flacco#15]
Hi,
First i really appreciate your work.
When installing as a R package as mentioned in the READ_ME, the functions for computing features are not found. In the NAMESPACE file, i checked that they are not exported.
Do we need extra packages that are not mentioned? 

I would appreciate if you could tell me exactly how i can make it work

Thank you

**Comment by kerschke** [comment]
Hi and thanks for asking. Currently, I do not recommend to use the current version of the package as it is still heavy work in progress. A clean version of the package should be online by the end of the month..
Hope, you still can wait until then?!
