### ISSUE TITLE
coverall skips majority of tests

### ISSUE THREAD

**Issue by kerschke** [kerschke/flacco#23]
@mllg: I know that this is not related to any of your packages, but do you have any idea, why coverall skips the majority of my tests? Actually, it appears as if it is only running `test_check("flacco", filter = "^base")` although it should also run tests for other filters.

``` r
library(testthat)

# test general stuff:
test_check("flacco", filter = "^base")

# if (identical(Sys.getenv("TRAVIS"), "true") || identical(Sys.getenv("R_EXPENSIVE_TEST_OK"), "true")) {
  test_check("flacco", filter = "^plot")
# }
```

and

``` r
library(testthat)

# test features:
# if (identical(Sys.getenv("TRAVIS"), "true") || identical(Sys.getenv("R_EXPENSIVE_TEST_OK"), "true")) {
  test_check("flacco", filter = "^cm")
  test_check("flacco", filter = "^ela")
  test_check("flacco", filter = "^gcm")
  test_check("flacco", filter = "^ic")
  test_check("flacco", filter = "^misc")
  test_check("flacco", filter = "calculateFeatures")
# }
```

I was already guessing that it might be caused by the if-check prior to these tests (although it used to work until the beginning of February) - but comments around that `if`-clause do not help either :-/

**Comment by mllg** [comment]
Try installing the github version of covr for travis and also check the output of `rcov` / `rcov --shine` (in rt) locally

**Comment by kerschke** [comment]
Hmm.. The github version only works on the devel but not the release branch on travis (https://travis-ci.org/kerschke/flacco/builds/120831807).

When I try to run `rcov` locally from my console, I get the following:

```
flacco Pascal$ rcov
Loading required namespace: covr
Checking code coverage of package 'flacco' ...
Error: invalid 'path' argument
```

Same problem from within R Studio

``` r
> rcov(".")
Loading required namespace: covr
Checking code coverage of package 'flacco' ...
Error in path.expand(path) : invalid 'path' argument
```

**Comment by kerschke** [comment]
And I am in the correct path (`rtest` for instance runs fine).

**Comment by kerschke** [comment]
I think I see the problem in `rcov`:

``` r
rcov = function(path = getwd(), shine = FALSE) {
  pkg = devtools::as.package(path, create = FALSE)

  if (!requireNamespace("covr"))
    stop("Please install package 'covr'")

  messagef("Checking code coverage of package '%s' ...", pkg$package)
  coverage = covr::package_coverage(pkg)
  print(coverage)
  if (shine)
    covr::shine(coverage)
  invisible(TRUE)
}
```

When computing the coverage, the argument should be `path` and not `pkg`.

**Comment by kerschke** [comment]
The good thing is that `covr` now (locally) shows 100% coverage for all of my tests. Unfortunately, that only solves my local problem.
The main problem remains the proper test evaluation from within coverall or being more precise, finding the reason why coverall ignores the majority of the tests.

**Comment by kerschke** [comment]
> Hmm.. The github version only works on the devel but not the release branch on travis (https://travis-ci.org/kerschke/flacco/builds/120831807).

After switching the coverage-call from `Rscript -e 'library(covr);coveralls()'` to `Rscript -e 'covr::coveralls()'`, both builds work on travis (https://travis-ci.org/kerschke/flacco/builds/120844302). However, the faulty coverage remains :-/

**Comment by kerschke** [comment]
Actually, I am surprised that coverall shows something at all, because the call from within travis fails:

```
$ Rscript -e 'covr::coveralls()'

Error in covr::coveralls() : 

  Failed to upload coverage data. Reply by Coveralls: Couldn't find a repository matching this job.

Execution halted
```

**Comment by kerschke** [comment]
seems to work by now.. will re-open in case the issue occurs again.
