### ISSUE TITLE
Latin Hyper-Cube malfunction?

### ISSUE THREAD

**Issue by annabosman** [kerschke/flacco#24]
I am trying to use FLACCO to characterise neural network error surfaces. I got the CRAN version of the library, and I get the following error when attempting to create an initial sample with a latin hypercube:

`X = createInitialSample(n.obs = 1000, control=list(init_sample.type = "lhs", init_sample.lower = -5, init_sample.upper = 5), dim = calcDim(irisArch))`

The result is:

`Error in loadNamespace(name) : there is no package called ‘lhs’`

The issue arises only with lhs. The random option works fine. However, if I understand Mersmann's paper correctly, latin hypercube is not really optional.

**Comment by kerschke** [comment]
Did you actually install the `lhs`-package?
It is available on CRAN: https://cran.r-project.org/web/packages/lhs/index.html

Just type `install.packages("lhs")` within your R console.

**Comment by annabosman** [comment]
I didn't - thanks for pointing it out! I made an unfair assumption that FLACCO would take care of all dependencies.

**Comment by kerschke** [comment]
Cool :) So far, I decided not to force the installation of all dependencies which are not completely necessary for using FLACCO.
