### ISSUE TITLE
Improve usage of feature computation

### ISSUE THREAD

**Issue by kerschke** [kerschke/flacco#9]
Function names should be more intuitive and useful, e.g. `calculateConvexityFeatures` instead of `calculateConvexity`. I plan to do the following changes.

Cell Mapping:
(1) `calculateAngle` --> `calculateAngleFeatures`
(2) `calculateCellConvexity` --> `calculateCellConvexityFeatures`
(3) `calculateGradientHomogeneity` --> `calculateGradientHomogeneityFeatures`

ELA:
(1) `calculateConvexity` --> `calculateConvexityFeatures`
(2) `calculateCurvature` --> `calculateCurvatureFeatures`
(3) `calculateLevelset` --> `calculateLevelsetFeatures`
(4) `calculateLocalSearch` --> `calculateLocalSearchFeatures`
(5) `calculateMetaModel` --> `calculateMetaModelFeatures`
(6) `calculateDistribution` --> `calculateDistributionFeatures`

Misc:
(1) `calculateBasics` --> `calculateBasicFeatures`
(2) `calculateDispersion` --> `calculateDispersionFeatures`
(3) `calculateLinModCoefficients` --> `calculateLinearModelFeatures`
(4) `calculateNearestBetter` --> `calculateNearestBetterFeatures`
(5) `calculatePCA` --> `calculatePrincipalComponentFeatures`

**Comment by kerschke** [comment]
Also, there should be a wrapper function `calculateFeatureSet(feat.object, set, control)` that takes a character for the argument `set` and internally calls the corresponding feature computation function.

For instance, one should be able to call `calculateFeatureSet(feat.object = feat.object, set = "angle")` instead of `calculateAngleFeatures(feat.object = feat.object)`.

**Comment by kerschke** [comment]
In addition, there should be a function `listAvailableFeatures` and a function `calculateFeatures` that lists (or calculates, respectively) all available features -- also allowing to make certain restrictions such as only listing features, which do not need additional function evaluations or don't require cell mapping.

**Comment by kerschke** [comment]
The first two items of this issue are solved. Also, the function `listAvailableFeatures` exists.
So far, only a function is missing, which computes all the features at once (`calculateFeatures`).

**Comment by kerschke** [comment]
Ok, now there's also a function `calculateFeatures`. However, as the gcm and ic features still are in a different format (they return lists of lists instead of lists of features), those aren't yet considered.
@Dagefoerde Could you make sure that the features are returned within the same format and then integrate them in this function? And remember to test them :-)

**Comment by Dagefoerde** [comment]
I updated the return value format and updated the tests accordingly.
